### ISSUE TITLE
check-package.TestPackage.testDiscard is flaky

### ISSUE THREAD

**Issue by larskarlitski** [osbuild/cockpit-composer#1005]
The `check-package.TestPackage.testDiscard` test sometimes fails in RHEL gating. I couldn't reproduce this locally yet.

```
# 1 TEST FAILED [59s on ibm-p8-kvm-03-guest-02]
Started /usr/lib64/chromium-browser/headless_shell (pid 63546) on port 10103
Traceback (most recent call last):
  File "test/verify/check-package", line 219, in testDiscard
    b.click("li[data-input=cockpit-composer] .fa-plus")
  File "/var/str/source/test/common/testlib.py", line 215, in click
    self.mouse(selector + ":not([disabled])", "click", 0, 0, 0)
  File "/var/str/source/test/common/testlib.py", line 212, in mouse
    self.call_js_func('ph_mouse', selector, type, x, y, btn, ctrlKey, shiftKey, altKey, metaKey)
  File "/var/str/source/test/common/testlib.py", line 196, in call_js_func
    return self.eval_js("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/var/str/source/test/common/testlib.py", line 180, in eval_js
    silent=False, awaitPromise=True, returnByValue=True, no_trace=no_trace)
  File "/var/str/source/test/common/cdp.py", line 109, in invoke
    res = self.command(cmd)
  File "/var/str/source/test/common/cdp.py", line 136, in command
    raise RuntimeError(res["error"])
RuntimeError: TypeError: Cannot read property 'concat' of undefined
```

**Comment by jkozol** [comment]
I am hopefully this is fixed but won't close until after the next rhel release.

**Comment by jkozol** [comment]
This test did not flake in the recent rhel 8-3 release so I will close it now.
