### ISSUE TITLE
OSTreeCommit test fails

### ISSUE THREAD

**Issue by jkozol** [osbuild/cockpit-composer#1294]
The OSTreeCommit test consistently fails. I was able to replicate this failure locally and check the image logs. This is the failure message in the image's log:

```
Output:
/usr/lib/tmpfiles.d/journal-nocow.conf:26: Failed to resolve specifier: uninitialized /etc detected, skipping
All rules containing unresolvable specifiers will be skipped.
Failed to open file "/sys/fs/selinux/checkreqprot": Read-only file system
Initializing root filesystem
Copying data
fuse: device not found, try 'modprobe fuse' first
fuse: device not found, try 'modprobe fuse' first
bwrap: execvp true: No such file or directory
fusermount: failed to unmount /tmp/rpmostree-rofiles-fuseTmK2YZ: Invalid argument
fusermount: failed to unmount /tmp/rpmostree-rofiles-fuseEz4de2: Invalid argument
error: bwrap test failed, see <https://github.com/coreos/rpm-ostree/pull/429>: bwrap(true): Child process killed by signal 1
Traceback (most recent call last):
  File "/run/osbuild/bin/org.osbuild.ostree.commit", line 190, in <module>
    r = main(args_input, args_output, args["options"], args["meta"])
  File "/run/osbuild/bin/org.osbuild.ostree.commit", line 162, in main
    subprocess.run(argv,
  File "/usr/lib64/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['rpm-ostree', 'compose', 'commit', '--repo=/run/osbuild/tree/repo', '--add-metadata-string=rpmostree.inputhash=7194f8c94e47a572d772805b4fbe4820a347e22ddcfc666d28b2572a862db90c', '--write-composejson-to=/run/osbuild/tree/compose.json', '/tmp/tmph1u20mt3.json', '/run/osbuild/tree/tmpdm5njnol']' returned non-zero exit status 1.
```

@henrywang Have you had any luck replicating this failure? Have you seen a similar failure message?

@gicmo Have you seen any failure like this for ostree?

@martinpitt @marusak Have there been any changes to cockpit's fedora 33 testing images that might cause an issue with fuse or bwrap?

**Comment by martinpitt** [comment]
@jkozol : We got several image refreshes, but as TestLargeSystem has failed for so long, we started to ignore these failures. So it's plausible that something in rpm-ostree/bwrap/fuse/etc. regressed recently.

**Comment by gicmo** [comment]
So this is the `bwrap` selftest inside our build root failing, from the python version I assume this trying to build F34? I wonder if it is working locally.

**Comment by jkozol** [comment]
@gicmo It should be trying to build fedora 33 since it is running on a fedora 33 vm.
